# Generated by Django 4.2.7 on 2025-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxiGPSLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("car_plate", models.CharField(max_length=32, verbose_name="车牌号")),
                ("beijing_time", models.DateTimeField(verbose_name="北京时间")),
                ("gcj02_lat", models.FloatField(verbose_name="GCJ02纬度")),
                ("gcj02_lon", models.FloatField(verbose_name="GCJ02经度")),
                (
                    "heading",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="方向"
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(blank=True, null=True, verbose_name="是否载客"),
                ),
                (
                    "event_tag",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="事件标签"
                    ),
                ),
                (
                    "trip_id",
                    models.IntegerField(blank=True, null=True, verbose_name="行程ID"),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, null=True, verbose_name="速度"),
                ),
            ],
            options={
                "verbose_name": "出租车GPS日志",
                "verbose_name_plural": "出租车GPS日志",
                "db_table": "taxi_gps_log",
                "managed": False,
            },
        ),
    ]
